/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passman;

import java.awt.CardLayout;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import java.util.Base64;
import javax.swing.JFrame;
/*import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;*/
import passman.db.SQLiteJDBC;
import passman.model.Model;
import passman.model.PassGenerator;
import passman.db.Crypt;
import passman.model.CryptModel;
import passman.model.ErrorDialog;
import passman.model.User;
//import passman.Utils;

/**
 *
 * @author P057736
 */
public class PassManUI extends javax.swing.JFrame {

    /**
     * Creates new form PassManUI
     */
    public PassManUI() {
        initComponents();
    }
    
    Utils utils = new Utils();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupWindow = new javax.swing.JDialog();
        okPopupWinBtn = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        loginPassword = new javax.swing.JPasswordField();
        loginUsername = new javax.swing.JTextField();
        attemptLogin = new javax.swing.JButton();
        createAccBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        addEntryBtn = new javax.swing.JButton();
        viewListBtn = new javax.swing.JButton();
        globalViewPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        labelShow = new javax.swing.JTextField();
        usernameShow = new javax.swing.JTextField();
        passwordShow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        removeEntryBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentShow = new javax.swing.JTextArea();
        toggleShowPassword = new javax.swing.JToggleButton();
        addEntryPane = new javax.swing.JPanel();
        newLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmEntryBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        newUsername = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newComment = new javax.swing.JTextArea();
        languagePane = new javax.swing.JPanel();
        portuguese = new javax.swing.JRadioButton();
        english = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        createUserPane = new javax.swing.JPanel();
        newUserField = new javax.swing.JTextField();
        newUserPasswordField = new javax.swing.JPasswordField();
        newUserPasswordField2 = new javax.swing.JPasswordField();
        createUserBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEntry = new javax.swing.JMenuItem();
        viewList = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        languageMenu = new javax.swing.JMenuItem();

        popupWindow.setMinimumSize(new java.awt.Dimension(300, 200));

        okPopupWinBtn.setText("null");
        okPopupWinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPopupWinBtnActionPerformed(evt);
            }
        });

        message.setText("jLabel11");

        javax.swing.GroupLayout popupWindowLayout = new javax.swing.GroupLayout(popupWindow.getContentPane());
        popupWindow.getContentPane().setLayout(popupWindowLayout);
        popupWindowLayout.setHorizontalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupWindowLayout.createSequentialGroup()
                .addGroup(popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(okPopupWinBtn))
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(message)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        popupWindowLayout.setVerticalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupWindowLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(okPopupWinBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 345));

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPassword.setMinimumSize(new java.awt.Dimension(110, 20));
        loginPassword.setPreferredSize(new java.awt.Dimension(110, 20));

        loginUsername.setMinimumSize(new java.awt.Dimension(110, 20));
        loginUsername.setPreferredSize(new java.awt.Dimension(110, 20));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("passman/Bundle"); // NOI18N
        attemptLogin.setText(bundle.getString("LOGIN")); // NOI18N
        attemptLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptLoginActionPerformed(evt);
            }
        });

        createAccBtn.setText(bundle.getString("CREATEACC")); // NOI18N
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });

        jLabel11.setText(bundle.getString("USERNAME")); // NOI18N

        jLabel12.setText(bundle.getString("PASSWORD")); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText(bundle.getString("PLEASELOGIN")); // NOI18N

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createAccBtn)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPaneLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(attemptLogin))
                            .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel16)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAccBtn)
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attemptLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(loginPane, "LOGIN");

        mainPane.setBackground(new java.awt.Color(51, 163, 252));
        mainPane.setLayout(new java.awt.GridBagLayout());

        addEntryBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        addEntryBtn.setText(bundle.getString("ADD")); // NOI18N
        addEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPane.add(addEntryBtn, gridBagConstraints);

        viewListBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        viewListBtn.setText(bundle.getString("VIEW")); // NOI18N
        viewListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPane.add(viewListBtn, gridBagConstraints);

        mainPanel.add(mainPane, "MAIN");

        globalViewPane.setToolTipText(bundle.getString("SHOW")); // NOI18N

        jList1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jList1ComponentShown(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        labelShow.setEditable(false);

        usernameShow.setEditable(false);

        passwordShow.setEditable(false);
        passwordShow.setText("null");

        jLabel1.setText(bundle.getString("USERNAME")); // NOI18N

        jLabel5.setText(bundle.getString("PASSWORD")); // NOI18N

        removeEntryBtn.setText(bundle.getString("REMOVE")); // NOI18N
        removeEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEntryBtnActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("LABEL")); // NOI18N

        jLabel3.setText(bundle.getString("COMMENTS")); // NOI18N

        commentShow.setEditable(false);
        commentShow.setColumns(20);
        commentShow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        commentShow.setLineWrap(true);
        commentShow.setRows(5);
        commentShow.setWrapStyleWord(true);
        jScrollPane3.setViewportView(commentShow);

        toggleShowPassword.setText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.setToolTipText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePassVisibility(evt);
            }
        });

        javax.swing.GroupLayout globalViewPaneLayout = new javax.swing.GroupLayout(globalViewPane);
        globalViewPane.setLayout(globalViewPaneLayout);
        globalViewPaneLayout.setHorizontalGroup(
            globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(globalViewPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(globalViewPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, globalViewPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, globalViewPaneLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameShow, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, globalViewPaneLayout.createSequentialGroup()
                                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, globalViewPaneLayout.createSequentialGroup()
                                        .addComponent(passwordShow)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(toggleShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(globalViewPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(removeEntryBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        globalViewPaneLayout.setVerticalGroup(
            globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(globalViewPaneLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(removeEntryBtn)
                .addGap(18, 18, 18)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(toggleShowPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainPanel.add(globalViewPane, "GLOBAL");

        newLabel.setMinimumSize(new java.awt.Dimension(100, 25));
        newLabel.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel4.setLabelFor(newUsername);
        jLabel4.setText(bundle.getString("USERNAME")); // NOI18N

        confirmEntryBtn.setText(bundle.getString("CREATE")); // NOI18N
        confirmEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEntryBtnActionPerformed(evt);
            }
        });

        jLabel7.setLabelFor(newPassword);
        jLabel7.setText(bundle.getString("PASSWORD")); // NOI18N

        newUsername.setMinimumSize(new java.awt.Dimension(100, 25));
        newUsername.setPreferredSize(new java.awt.Dimension(100, 25));

        newPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        newPassword.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel9.setText(bundle.getString("LABEL")); // NOI18N

        jLabel10.setText(bundle.getString("COMMENTS")); // NOI18N

        generateBtn.setText(bundle.getString("GENERATE")); // NOI18N
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        newComment.setColumns(20);
        newComment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newComment.setLineWrap(true);
        newComment.setRows(4);
        newComment.setWrapStyleWord(true);
        jScrollPane2.setViewportView(newComment);

        javax.swing.GroupLayout addEntryPaneLayout = new javax.swing.GroupLayout(addEntryPane);
        addEntryPane.setLayout(addEntryPaneLayout);
        addEntryPaneLayout.setHorizontalGroup(
            addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEntryPaneLayout.createSequentialGroup()
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(newLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmEntryBtn)))
                .addGap(21, 21, 21))
        );
        addEntryPaneLayout.setVerticalGroup(
            addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEntryPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn))
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10))
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(confirmEntryBtn)
                .addContainerGap())
        );

        mainPanel.add(addEntryPane, "ADD");

        buttonGroup1.add(portuguese);
        portuguese.setText(bundle.getString("PORTUGUESE")); // NOI18N
        portuguese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portugueseActionPerformed(evt);
            }
        });

        buttonGroup1.add(english);
        english.setText(bundle.getString("ENGLISH")); // NOI18N
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("BELOW YOU CAN CHOOSE YOUR PREFERRED LANGUAGE.")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel8.setText(bundle.getString("CHANGES WILL ONLY BE VISIBLE AFTER RESTARTING THE APPLICATION.")); // NOI18N

        homeBtn.setText(bundle.getString("BACK")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languagePaneLayout = new javax.swing.GroupLayout(languagePane);
        languagePane.setLayout(languagePaneLayout);
        languagePaneLayout.setHorizontalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(english)
                    .addComponent(portuguese)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languagePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );
        languagePaneLayout.setVerticalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(portuguese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(english)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );

        mainPanel.add(languagePane, "LANGUAGE");

        newUserField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserField.setPreferredSize(new java.awt.Dimension(110, 20));

        newUserPasswordField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField.setPreferredSize(new java.awt.Dimension(110, 20));

        newUserPasswordField2.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField2.setPreferredSize(new java.awt.Dimension(110, 20));

        createUserBtn.setText(bundle.getString("CONFIRMACC")); // NOI18N
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        jLabel13.setText(bundle.getString("USERNAME")); // NOI18N

        jLabel14.setText(bundle.getString("PASSWORD")); // NOI18N

        jLabel15.setText(bundle.getString("REPEATPASS")); // NOI18N

        javax.swing.GroupLayout createUserPaneLayout = new javax.swing.GroupLayout(createUserPane);
        createUserPane.setLayout(createUserPaneLayout);
        createUserPaneLayout.setHorizontalGroup(
            createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUserPaneLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUserPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185))
            .addGroup(createUserPaneLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(createUserBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createUserPaneLayout.setVerticalGroup(
            createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPaneLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createUserBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(createUserPane, "CREATEUSER");

        jMenu1.setText(bundle.getString("FILE")); // NOI18N
        jMenu1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        addEntry.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addEntry.setText(bundle.getString("ADD")); // NOI18N
        addEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryActionPerformed(evt);
            }
        });
        jMenu1.add(addEntry);

        viewList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewList.setText(bundle.getString("VIEW")); // NOI18N
        viewList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListActionPerformed(evt);
            }
        });
        jMenu1.add(viewList);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("EDIT")); // NOI18N
        jMenu2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        languageMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        languageMenu.setText(bundle.getString("LANGUAGE")); // NOI18N
        languageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageMenuActionPerformed(evt);
            }
        });
        jMenu2.add(languageMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is triggered when the user clicks the "Add" button.
     * @param evt 
     */
    private void addEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
        //removeEntryBtn.setEnabled(false);
    }//GEN-LAST:event_addEntryActionPerformed

    /**
     * This is triggered when the user clicks the "Create" button.
     * @param evt 
     */
    private void confirmEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEntryBtnActionPerformed
        // Get values from text fields
        String label = newLabel.getText();
        String username = newUsername.getText();
        String plainTextPassword = newPassword.getText();
        String comment = newComment.getText();
        // Calls method that encrypts the password using the current user values and saves entry to DB
        Utils.addToDBFromUI(label, username, plainTextPassword, comment);
        
        // clears fields
        newLabel.setText(""); //NOI18N
        newUsername.setText(""); //NOI18N
        newPassword.setText(""); //NOI18N
        newComment.setText(""); //NOI18N
        
        // moves to main screen
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_confirmEntryBtnActionPerformed

    private void jList1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jList1ComponentShown

    }//GEN-LAST:event_jList1ComponentShown

    /**
     * This is triggered when the user changes his list selection
     * @param evt 
     */
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex()>-1){
            // convert jList1 item to a Model item
            Model thisModel = (Model)jList1.getSelectedValue();
            
            // shows label, username and comments
            labelShow.setText(thisModel.getLabel());
            usernameShow.setText(thisModel.getUsername());
            commentShow.setText(thisModel.getComment());
            
            // only shows password if toggle is selected
            if(toggleShowPassword.isSelected()){
                String plainTextPassword = Utils.getFromDBToUI(thisModel.getPassword());
                
                passwordShow.setText(plainTextPassword);
            }
            // Enable remove button
            removeEntryBtn.setEnabled(true);
        }
        else{
            // Disable remove button
            removeEntryBtn.setEnabled(false);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void viewListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListBtnActionPerformed
        
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
        
        removeEntryBtn.setEnabled(false);
        
    }//GEN-LAST:event_viewListBtnActionPerformed

    private void addEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryBtnActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addEntryBtnActionPerformed

    private void viewListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListActionPerformed
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
    }//GEN-LAST:event_viewListActionPerformed

    private void removeEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEntryBtnActionPerformed
        Model model = (Model)jList1.getSelectedValue();
        
        SQLiteJDBC sqlite = new SQLiteJDBC();
        sqlite.removeItem2(model);
        
        utils.refreshView(jList1, mainPanel);
        //Utils.goToScreen(mainPanel, "GLOBAL");
        jList1.setSelectedIndex(0);
    }//GEN-LAST:event_removeEntryBtnActionPerformed

    private void languageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageMenuActionPerformed
        if(Utils.loadParams().get(1).equals("pt")){ //NOI18N
            portuguese.setSelected(true);
        }
        else {
            english.setSelected(true);
        }
        Utils.goToScreen(mainPanel, "LANGUAGE"); //NOI18N
    }//GEN-LAST:event_languageMenuActionPerformed

    private void portugueseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portugueseActionPerformed
        utils.saveParamChanges("pt", "PT"); //NOI18N
    }//GEN-LAST:event_portugueseActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        utils.saveParamChanges("en", "UK"); //NOI18N
    }//GEN-LAST:event_englishActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_homeBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        newPassword.setText(PassGenerator.generate());        
    }//GEN-LAST:event_generateBtnActionPerformed

    private void okPopupWinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPopupWinBtnActionPerformed
        // disposes popup window
        popupWindow.dispose();
    }//GEN-LAST:event_okPopupWinBtnActionPerformed

    /**
     * This is triggered when the user toggles the password visibility
     * @param evt 
     */
    private void togglePassVisibility(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePassVisibility
        if(toggleShowPassword.isSelected()){
            Model thisModel = (Model)jList1.getSelectedValue();
            String plainTextPassword = Utils.getFromDBToUI(thisModel.getPassword());

            passwordShow.setText(plainTextPassword);
        } else{
            passwordShow.setText("*********"); //NOI18N
        }
    }//GEN-LAST:event_togglePassVisibility

    /**
     * This is triggered when the user wants to login
     * @param evt 
     */
    private void attemptLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptLoginActionPerformed
        // Creates hash pass and user
        
        // fetches the user from DB
        SQLiteJDBC sqlite = new SQLiteJDBC();
        User compareUser = sqlite.getUser(loginUsername.getText());
        if(compareUser != null){
            byte[] salt = compareUser.getSaltArray();
            byte[] secPassword = compareUser.getSecurePassword();
            byte[] result = Crypt.verifyPasswordValidity(new String(loginPassword.getPassword()), salt, secPassword);
            
            if(result != null){
                // Sets the current user
                Utils.setCurrentUser(compareUser.getUsername());
                
                // Goes to main screen
                Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
            }
        }
    }//GEN-LAST:event_attemptLoginActionPerformed

    /**
     * This is triggered when the user wants to create an account
     * @param evt 
     */
    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        Utils.goToScreen(mainPanel, "CREATEUSER"); //NOI18N
    }//GEN-LAST:event_createAccBtnActionPerformed

    /**
     * This is triggered when the user confirms the creation of an account
     * @param evt 
     */
    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        if(Arrays.equals(newUserPasswordField.getPassword(),newUserPasswordField2.getPassword())){
            if(!newUserField.getText().isEmpty()){
                
                // Creates hash pass and user                
                ArrayList<byte[]> list = Crypt.getSecurePassword(new String(newUserPasswordField.getPassword()));
                User user = new User(newUserField.getText(), list.get(0), list.get(1));
                
                // adds user to DB
                SQLiteJDBC sqlite = new SQLiteJDBC();
                sqlite.addUser(user);
                
                // Clears fields
                newUserPasswordField.setText(""); //NOI18N
                newUserPasswordField2.setText(""); //NOI18N
                
                // Goes to login screen
                Utils.goToScreen(mainPanel, "LOGIN"); //NOI18N
            }
        }
    }//GEN-LAST:event_createUserBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("passman/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Set location (language) according to user preferences
        Locale.setDefault(new Locale(Utils.loadParams().get(1),Utils.loadParams().get(0)));

        // Creates DB if it doesn't exist
        Utils.verifyDB();
        
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PassManUI myFrame = new PassManUI();
                myFrame.setTitle(Utils.getTitleFromProps());
                myFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEntry;
    private javax.swing.JButton addEntryBtn;
    private javax.swing.JPanel addEntryPane;
    private javax.swing.JButton attemptLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea commentShow;
    private javax.swing.JButton confirmEntryBtn;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JPanel createUserPane;
    private javax.swing.JRadioButton english;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel globalViewPane;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField labelShow;
    private javax.swing.JMenuItem languageMenu;
    private javax.swing.JPanel languagePane;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea newComment;
    private javax.swing.JTextField newLabel;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField newUserField;
    private javax.swing.JPasswordField newUserPasswordField;
    private javax.swing.JPasswordField newUserPasswordField2;
    private javax.swing.JTextField newUsername;
    private javax.swing.JButton okPopupWinBtn;
    private javax.swing.JTextField passwordShow;
    private javax.swing.JDialog popupWindow;
    private javax.swing.JRadioButton portuguese;
    private javax.swing.JButton removeEntryBtn;
    private javax.swing.JToggleButton toggleShowPassword;
    private javax.swing.JTextField usernameShow;
    private javax.swing.JMenuItem viewList;
    private javax.swing.JButton viewListBtn;
    // End of variables declaration//GEN-END:variables
}
