/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passman;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import passman.db.SQLiteJDBC;
import passman.model.Model;
import passman.model.PassGenerator;
import passman.db.Crypt;
import passman.model.User;
import java.awt.datatransfer.*;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JFrame;
import passman.model.ErrorDialog;
//import passman.Utils;

/**
 *
 * @author P057736
 */
public class PassManUI extends javax.swing.JFrame {

    /**
     * Creates new form PassManUI
     */
    public PassManUI() {
        initComponents();
    }
    
    Utils utils = new Utils();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupWindow = new javax.swing.JDialog();
        okPopupWinBtn = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginUsername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        loginPassword = new javax.swing.JPasswordField();
        attemptLogin = new javax.swing.JButton();
        mainPane = new javax.swing.JPanel();
        addEntryBtn = new javax.swing.JButton();
        viewListBtn = new javax.swing.JButton();
        globalViewPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        removeEntryBtn = new javax.swing.JButton();
        toggleShowPassword = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        labelShow = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        usernameShow = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordShow = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentShow = new javax.swing.JTextArea();
        addNewEntryBtn = new javax.swing.JButton();
        copyToClip = new javax.swing.JButton();
        addEntryPane = new javax.swing.JPanel();
        newLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmEntryBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        newUsername = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newComment = new javax.swing.JTextArea();
        languagePane = new javax.swing.JPanel();
        portuguese = new javax.swing.JRadioButton();
        english = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        createUserPane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        newUserField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        newUserPasswordField = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        newUserPasswordField2 = new javax.swing.JPasswordField();
        createUserBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        createAccMenuItem = new javax.swing.JMenuItem();
        addEntry = new javax.swing.JMenuItem();
        viewList = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        languageMenu = new javax.swing.JMenuItem();

        popupWindow.setMinimumSize(new java.awt.Dimension(300, 200));

        okPopupWinBtn.setText("null");
        okPopupWinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPopupWinBtnActionPerformed(evt);
            }
        });

        message.setText("jLabel11");

        javax.swing.GroupLayout popupWindowLayout = new javax.swing.GroupLayout(popupWindow.getContentPane());
        popupWindow.getContentPane().setLayout(popupWindowLayout);
        popupWindowLayout.setHorizontalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupWindowLayout.createSequentialGroup()
                .addGroup(popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(okPopupWinBtn))
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(message)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        popupWindowLayout.setVerticalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupWindowLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(okPopupWinBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        setMaximumSize(new java.awt.Dimension(450, 300));
        setMinimumSize(new java.awt.Dimension(450, 300));
        setPreferredSize(new java.awt.Dimension(450, 300));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${maximumSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("maximumSize"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${minimumSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("preferredSize"));
        bindingGroup.addBinding(binding);

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPane.setBackground(new java.awt.Color(51, 163, 252));
        loginPane.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        loginPane.setMaximumSize(new java.awt.Dimension(450, 300));
        loginPane.setMinimumSize(new java.awt.Dimension(450, 300));
        loginPane.setPreferredSize(new java.awt.Dimension(450, 300));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("passman/Bundle"); // NOI18N
        jLabel16.setText(bundle.getString("PLEASELOGIN")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(loginUsername);
        jLabel11.setText(bundle.getString("USERNAME")); // NOI18N

        loginUsername.setMinimumSize(new java.awt.Dimension(110, 20));
        loginUsername.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(loginPassword);
        jLabel12.setText(bundle.getString("PASSWORD")); // NOI18N

        loginPassword.setMinimumSize(new java.awt.Dimension(110, 20));
        loginPassword.setPreferredSize(new java.awt.Dimension(110, 20));

        attemptLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        attemptLogin.setText(bundle.getString("LOGIN")); // NOI18N
        attemptLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attemptLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(loginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attemptLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mainPanel.add(loginPane, "LOGIN");

        mainPane.setBackground(new java.awt.Color(51, 163, 252));

        addEntryBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        addEntryBtn.setText(bundle.getString("ADD")); // NOI18N
        addEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryBtnActionPerformed(evt);
            }
        });

        viewListBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        viewListBtn.setText(bundle.getString("VIEW")); // NOI18N
        viewListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addEntryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(558, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addEntryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(mainPane, "MAIN");

        globalViewPane.setBackground(new java.awt.Color(51, 163, 252));
        globalViewPane.setToolTipText(bundle.getString("SHOW")); // NOI18N
        globalViewPane.setMaximumSize(new java.awt.Dimension(450, 300));
        globalViewPane.setMinimumSize(new java.awt.Dimension(450, 300));
        globalViewPane.setPreferredSize(new java.awt.Dimension(450, 300));

        jList1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        removeEntryBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        removeEntryBtn.setText(bundle.getString("REMOVE")); // NOI18N
        removeEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEntryBtnActionPerformed(evt);
            }
        });

        toggleShowPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        toggleShowPassword.setText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.setToolTipText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePassVisibility(evt);
            }
        });

        jLabel2.setText(bundle.getString("LABEL")); // NOI18N

        labelShow.setEditable(false);
        labelShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel1.setText(bundle.getString("USERNAME")); // NOI18N

        usernameShow.setEditable(false);
        usernameShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel5.setText(bundle.getString("PASSWORD")); // NOI18N

        passwordShow.setEditable(false);
        passwordShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        passwordShow.setText("null");
        passwordShow.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabel3.setText(bundle.getString("COMMENTS")); // NOI18N

        commentShow.setEditable(false);
        commentShow.setColumns(20);
        commentShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        commentShow.setLineWrap(true);
        commentShow.setRows(5);
        commentShow.setWrapStyleWord(true);
        jScrollPane3.setViewportView(commentShow);

        addNewEntryBtn.setText(bundle.getString("ADD")); // NOI18N
        addNewEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEntryBtnActionPerformed(evt);
            }
        });

        copyToClip.setText(bundle.getString("COPY")); // NOI18N
        copyToClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout globalViewPaneLayout = new javax.swing.GroupLayout(globalViewPane);
        globalViewPane.setLayout(globalViewPaneLayout);
        globalViewPaneLayout.setHorizontalGroup(
            globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(globalViewPaneLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(globalViewPaneLayout.createSequentialGroup()
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelShow, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameShow, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordShow, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(globalViewPaneLayout.createSequentialGroup()
                        .addComponent(removeEntryBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleShowPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNewEntryBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyToClip)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        globalViewPaneLayout.setVerticalGroup(
            globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(globalViewPaneLayout.createSequentialGroup()
                .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(globalViewPaneLayout.createSequentialGroup()
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeEntryBtn)
                            .addComponent(toggleShowPassword)
                            .addComponent(addNewEntryBtn)
                            .addComponent(copyToClip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usernameShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(globalViewPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        mainPanel.add(globalViewPane, "GLOBAL");

        addEntryPane.setBackground(new java.awt.Color(51, 163, 252));
        addEntryPane.setMaximumSize(new java.awt.Dimension(450, 300));
        addEntryPane.setMinimumSize(new java.awt.Dimension(450, 300));
        addEntryPane.setPreferredSize(new java.awt.Dimension(450, 300));

        newLabel.setMinimumSize(new java.awt.Dimension(100, 25));
        newLabel.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel4.setLabelFor(newUsername);
        jLabel4.setText(bundle.getString("USERNAME")); // NOI18N

        confirmEntryBtn.setText(bundle.getString("CREATE")); // NOI18N
        confirmEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEntryBtnActionPerformed(evt);
            }
        });

        jLabel7.setLabelFor(newPassword);
        jLabel7.setText(bundle.getString("PASSWORD")); // NOI18N

        newUsername.setMinimumSize(new java.awt.Dimension(100, 25));
        newUsername.setPreferredSize(new java.awt.Dimension(100, 25));

        newPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        newPassword.setPreferredSize(new java.awt.Dimension(100, 25));

        jLabel9.setText(bundle.getString("LABEL")); // NOI18N

        jLabel10.setText(bundle.getString("COMMENTS")); // NOI18N

        generateBtn.setText(bundle.getString("GENERATE")); // NOI18N
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        newComment.setColumns(20);
        newComment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newComment.setLineWrap(true);
        newComment.setRows(4);
        newComment.setWrapStyleWord(true);
        jScrollPane2.setViewportView(newComment);

        javax.swing.GroupLayout addEntryPaneLayout = new javax.swing.GroupLayout(addEntryPane);
        addEntryPane.setLayout(addEntryPaneLayout);
        addEntryPaneLayout.setHorizontalGroup(
            addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEntryPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(newLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(confirmEntryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateBtn)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        addEntryPaneLayout.setVerticalGroup(
            addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEntryPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBtn))
                .addGroup(addEntryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10))
                    .addGroup(addEntryPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmEntryBtn)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPanel.add(addEntryPane, "ADD");

        languagePane.setBackground(new java.awt.Color(51, 163, 252));
        languagePane.setMaximumSize(new java.awt.Dimension(450, 300));
        languagePane.setMinimumSize(new java.awt.Dimension(450, 300));
        languagePane.setPreferredSize(new java.awt.Dimension(450, 300));

        portuguese.setBackground(new java.awt.Color(51, 163, 252));
        buttonGroup1.add(portuguese);
        portuguese.setText(bundle.getString("PORTUGUESE")); // NOI18N
        portuguese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portugueseActionPerformed(evt);
            }
        });

        english.setBackground(new java.awt.Color(51, 163, 252));
        buttonGroup1.add(english);
        english.setText(bundle.getString("ENGLISH")); // NOI18N
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("BELOW YOU CAN CHOOSE YOUR PREFERRED LANGUAGE.")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel8.setText(bundle.getString("CHANGES WILL ONLY BE VISIBLE AFTER RESTARTING THE APPLICATION.")); // NOI18N

        homeBtn.setText(bundle.getString("BACK")); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languagePaneLayout = new javax.swing.GroupLayout(languagePane);
        languagePane.setLayout(languagePaneLayout);
        languagePaneLayout.setHorizontalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(english)
                    .addComponent(portuguese)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languagePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );
        languagePaneLayout.setVerticalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(portuguese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(english)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );

        mainPanel.add(languagePane, "LANGUAGE");

        createUserPane.setBackground(new java.awt.Color(51, 163, 252));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText(bundle.getString("USERNAME")); // NOI18N

        newUserField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserField.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText(bundle.getString("PASSWORD")); // NOI18N

        newUserPasswordField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText(bundle.getString("REPEATPASS")); // NOI18N

        newUserPasswordField2.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField2.setPreferredSize(new java.awt.Dimension(110, 20));

        createUserBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        createUserBtn.setText(bundle.getString("CONFIRMACC")); // NOI18N
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createUserPaneLayout = new javax.swing.GroupLayout(createUserPane);
        createUserPane.setLayout(createUserPaneLayout);
        createUserPaneLayout.setHorizontalGroup(
            createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(newUserField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(newUserPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUserPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        createUserPaneLayout.setVerticalGroup(
            createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(13, 13, 13)
                .addGroup(createUserPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        mainPanel.add(createUserPane, "CREATEUSER");

        jMenu1.setText(bundle.getString("FILE")); // NOI18N
        jMenu1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        createAccMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        createAccMenuItem.setText(bundle.getString("CREATEACC")); // NOI18N
        createAccMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(createAccMenuItem);

        addEntry.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addEntry.setText(bundle.getString("ADD")); // NOI18N
        addEntry.setEnabled(false);
        addEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryActionPerformed(evt);
            }
        });
        jMenu1.add(addEntry);

        viewList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewList.setText(bundle.getString("VIEW")); // NOI18N
        viewList.setEnabled(false);
        viewList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListActionPerformed(evt);
            }
        });
        jMenu1.add(viewList);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("EDIT")); // NOI18N
        jMenu2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        languageMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        languageMenu.setText(bundle.getString("LANGUAGE")); // NOI18N
        languageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageMenuActionPerformed(evt);
            }
        });
        jMenu2.add(languageMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is triggered when the user clicks the "Add" button.
     * @param evt 
     */
    private void addEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
        //removeEntryBtn.setEnabled(false);
    }//GEN-LAST:event_addEntryActionPerformed

    /**
     * This is triggered when the user clicks the "Create" button.
     * @param evt 
     */
    private void confirmEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEntryBtnActionPerformed
        // Get values from text fields
        String label = newLabel.getText();
        String username = newUsername.getText();
        String plainTextPassword = newPassword.getText();
        String comment = newComment.getText();
        // Calls method that encrypts the password using the current user values and saves entry to DB
        Utils.addToDBFromUI(label, username, plainTextPassword, comment);
        
        // clears fields
        newLabel.setText(""); //NOI18N
        newUsername.setText(""); //NOI18N
        newPassword.setText(""); //NOI18N
        newComment.setText(""); //NOI18N
        
        // moves to main screen
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_confirmEntryBtnActionPerformed

    /**
     * This is triggered when the user changes his list selection
     * @param evt 
     */
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(jList1.getSelectedIndex()>-1){
            // convert jList1 item to a Model item
            Model thisModel = (Model)jList1.getSelectedValue();
            
            // shows label, username and comments
            labelShow.setText(thisModel.getLabel());
            usernameShow.setText(thisModel.getUsername());
            commentShow.setText(thisModel.getComment());
            
            // only shows password if toggle is selected
            if(toggleShowPassword.isSelected()){
                String plainTextPassword = Utils.getFromDBToUI(thisModel.getPassword(),thisModel.getSalt());
                
                passwordShow.setText(plainTextPassword);
            } else{
                passwordShow.setText("*********");
            }
            // Enable remove button
            removeEntryBtn.setEnabled(true);
        }
        else{
            // Disable remove button
            removeEntryBtn.setEnabled(false);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void viewListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListBtnActionPerformed
        
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
        
        removeEntryBtn.setEnabled(false);
        
    }//GEN-LAST:event_viewListBtnActionPerformed

    private void addEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryBtnActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addEntryBtnActionPerformed

    private void viewListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListActionPerformed
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
    }//GEN-LAST:event_viewListActionPerformed

    private void languageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageMenuActionPerformed
        if(Utils.loadParams().get(1).equals("pt")){ //NOI18N
            portuguese.setSelected(true);
        }
        else {
            english.setSelected(true);
        }
        Utils.goToScreen(mainPanel, "LANGUAGE"); //NOI18N
    }//GEN-LAST:event_languageMenuActionPerformed

    private void portugueseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portugueseActionPerformed
        utils.saveParamChanges("pt", "PT"); //NOI18N
    }//GEN-LAST:event_portugueseActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        utils.saveParamChanges("en", "UK"); //NOI18N
    }//GEN-LAST:event_englishActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_homeBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        newPassword.setText(PassGenerator.generate());        
    }//GEN-LAST:event_generateBtnActionPerformed

    private void okPopupWinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPopupWinBtnActionPerformed
        // disposes popup window
        popupWindow.dispose();
    }//GEN-LAST:event_okPopupWinBtnActionPerformed

    /**
     * This is triggered when the user toggles the password visibility
     * @param evt 
     */
    private void togglePassVisibility(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePassVisibility
        if(toggleShowPassword.isSelected()){
            Model thisModel = (Model)jList1.getSelectedValue();
            String plainTextPassword = Utils.getFromDBToUI(thisModel.getPassword(),thisModel.getSalt());

            passwordShow.setText(plainTextPassword);
        } else{
            passwordShow.setText("*********"); //NOI18N
        }
    }//GEN-LAST:event_togglePassVisibility

    /**
     * This is triggered when the user confirms the creation of an account
     * @param evt 
     */
    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        if(Arrays.equals(newUserPasswordField.getPassword(),newUserPasswordField2.getPassword())){
            if(!newUserField.getText().isEmpty()){
                
                // Creates hash pass and user                
                ArrayList<byte[]> list = Crypt.getSecurePassword(new String(newUserPasswordField.getPassword()));
                User user = new User(newUserField.getText(), list.get(0), list.get(1));
                
                // adds user to DB
                SQLiteJDBC sqlite = new SQLiteJDBC();
                sqlite.addUser(user);
                
                // Clears fields
                newUserPasswordField.setText(""); //NOI18N
                newUserPasswordField2.setText(""); //NOI18N
                
                // Goes to login screen
                Utils.goToScreen(mainPanel, "LOGIN"); //NOI18N
            }
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void createAccMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccMenuItemActionPerformed
        Utils.goToScreen(mainPanel, "CREATEUSER"); //NOI18N
    }//GEN-LAST:event_createAccMenuItemActionPerformed

    /**
     * This is triggered when the user wants to login
     * @param evt 
     */
    private void attemptLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptLoginActionPerformed
        // Creates hash pass and user

        // fetches the user from DB
        SQLiteJDBC sqlite = new SQLiteJDBC();
        User compareUser = sqlite.getUser(loginUsername.getText());
        if(compareUser != null){
            byte[] salt = compareUser.getSaltArray();
            byte[] secPassword = compareUser.getSecurePassword();
            byte[] result = Crypt.verifyPasswordValidity(new String(loginPassword.getPassword()), salt, secPassword);

            if(result != null){
                // Sets the current user
                Utils.setCurrentUser(compareUser.getUsername());

                // Goes to main screen
                Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
                
                // Enables Menu options
                Component[] menuComps = jMenu1.getMenuComponents();
                for(Component comp : menuComps){
                    if(!comp.isEnabled()){
                        comp.setEnabled(true);
                    }
                }
                
                // Disables create account menu option
                createAccMenuItem.setEnabled(false);
                
                // Log action
                Logger.getLogger("").log(Level.INFO, "User {0} successfully logged in.",Utils.getCurrentUser());
            } else{
                // Log event
                Logger.getLogger("").log(Level.INFO, "User tried to login as {0} with a wrong password.", compareUser.getUsername());
            }
        }
    }//GEN-LAST:event_attemptLoginActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
        /*Dimension mainPanelDimension = mainPanel.getSize();
        // *** GLOBAL VIEW PANE *** //
        // Resize List
        Dimension newDim = new Dimension();
        newDim.height = (int)(mainPanelDimension.height*0.97);
        newDim.width = (int)(mainPanelDimension.width*0.25);
        jList1.setSize(newDim);
        jScrollPane1.setSize(newDim);*/
    }//GEN-LAST:event_formComponentResized

    private void removeEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEntryBtnActionPerformed
        Model model = (Model)jList1.getSelectedValue();

        SQLiteJDBC sqlite = new SQLiteJDBC();
        sqlite.removeItem2(model);

        utils.refreshView(jList1, mainPanel);

        // Clears text fields
        labelShow.setText("");
        usernameShow.setText("");
        passwordShow.setText("");
        commentShow.setText("");

        // Deselects items in list
        jList1.setSelectedIndex(-1);
    }//GEN-LAST:event_removeEntryBtnActionPerformed

    private void addNewEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEntryBtnActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addNewEntryBtnActionPerformed

    private void copyToClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipActionPerformed
        Model thisModel = (Model)jList1.getSelectedValue();
        String str = Utils.getFromDBToUI(thisModel.getPassword(),thisModel.getSalt());
        StringSelection stringSelection = new StringSelection (str);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_copyToClipActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("passman/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Logger config
        try{
            SimpleDateFormat format = new SimpleDateFormat("MM-dd");
            String logName = "PassManJ_logger%u_"+format.format(new Date())+".log";
            Handler handler = new FileHandler(logName, 10000, 1, true);
            handler.setFormatter(new SimpleFormatter());
            Logger.getLogger("").addHandler(handler);
        } catch(IOException | SecurityException e){
            ErrorDialog errDlg = new ErrorDialog(new JFrame(), e.getClass().getName(), e.getMessage());
            System.exit(0);
        }
                
        // Set location (language) according to user preferences
        List<String> list = Utils.loadParams();
        Locale.setDefault(new Locale(list.get(1),list.get(0)));

        // Creates DB if it doesn't exist
        Utils.verifyDB();
                
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PassManUI myFrame = new PassManUI();
                myFrame.setTitle(Utils.getTitleFromProps());
                myFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEntry;
    private javax.swing.JButton addEntryBtn;
    private javax.swing.JPanel addEntryPane;
    private javax.swing.JButton addNewEntryBtn;
    private javax.swing.JButton attemptLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea commentShow;
    private javax.swing.JButton confirmEntryBtn;
    private javax.swing.JButton copyToClip;
    private javax.swing.JMenuItem createAccMenuItem;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JPanel createUserPane;
    private javax.swing.JRadioButton english;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel globalViewPane;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField labelShow;
    private javax.swing.JMenuItem languageMenu;
    private javax.swing.JPanel languagePane;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea newComment;
    private javax.swing.JTextField newLabel;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField newUserField;
    private javax.swing.JPasswordField newUserPasswordField;
    private javax.swing.JPasswordField newUserPasswordField2;
    private javax.swing.JTextField newUsername;
    private javax.swing.JButton okPopupWinBtn;
    private javax.swing.JTextField passwordShow;
    private javax.swing.JDialog popupWindow;
    private javax.swing.JRadioButton portuguese;
    private javax.swing.JButton removeEntryBtn;
    private javax.swing.JToggleButton toggleShowPassword;
    private javax.swing.JTextField usernameShow;
    private javax.swing.JMenuItem viewList;
    private javax.swing.JButton viewListBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
