/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passman;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import passman.db.SQLiteJDBC;
import passman.model.Model;
import passman.model.PassGenerator;
import passman.db.Crypt;
import passman.model.User;
import java.awt.datatransfer.*;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.ListModel;
import passman.model.ChangePasswordDialog;
import passman.model.ChangeUsernameDialog;
import passman.model.DeleteAccountDialog;
import passman.model.ErrorDialog;
import passman.model.PasswordOptions;
import passman.model.PasswordOptionsDialog;
//import passman.Utils;

/**
 *
 * @author P057736
 */
public class PassManUI extends javax.swing.JFrame {

    /**
     * Creates new form PassManUI
     */
    public PassManUI() {
        initComponents();
    }
    
    Utils utils = new Utils();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupWindow = new javax.swing.JDialog();
        okPopupWinBtn = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        loginUsername = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        loginPassword = new javax.swing.JPasswordField();
        jPanel21 = new javax.swing.JPanel();
        attemptLogin = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        mainPane = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        addEntryBtn = new javax.swing.JButton();
        viewListBtn = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel12 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        quickSearchField = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        globalViewPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel3 = new javax.swing.JPanel();
        removeEntryBtn = new javax.swing.JButton();
        toggleShowPassword = new javax.swing.JToggleButton();
        addNewEntryBtn = new javax.swing.JButton();
        copyToClip = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelShow = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameShow = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passwordShow = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentShow = new javax.swing.JTextArea();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        addEntryPane = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        newLabel = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newUsername = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        pGenerationOptionsBtn = new javax.swing.JButton();
        newPassword = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newComment = new javax.swing.JTextArea();
        confirmEntryBtn = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        languagePane = new javax.swing.JPanel();
        portuguese = new javax.swing.JRadioButton();
        english = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        languageOK = new javax.swing.JButton();
        createUserPane = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        newUserField = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        newUserPasswordField = new javax.swing.JPasswordField();
        jPanel35 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        newUserPasswordField2 = new javax.swing.JPasswordField();
        jPanel31 = new javax.swing.JPanel();
        createUserBtn = new javax.swing.JButton();
        cancelCreateAcc = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        accountOptionsPane = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        changeUsernameButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        deleteAccBtn = new javax.swing.JButton();
        backFromAccOptsBtn = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        createAccMenuItem = new javax.swing.JMenuItem();
        addEntry = new javax.swing.JMenuItem();
        viewList = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        languageMenu = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenuItem();
        pGenerationMenuItem = new javax.swing.JMenuItem();

        popupWindow.setMinimumSize(new java.awt.Dimension(300, 200));

        okPopupWinBtn.setText("null");
        okPopupWinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPopupWinBtnActionPerformed(evt);
            }
        });

        message.setText("null");

        javax.swing.GroupLayout popupWindowLayout = new javax.swing.GroupLayout(popupWindow.getContentPane());
        popupWindow.getContentPane().setLayout(popupWindowLayout);
        popupWindowLayout.setHorizontalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupWindowLayout.createSequentialGroup()
                .addGroup(popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(okPopupWinBtn))
                    .addGroup(popupWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(message)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        popupWindowLayout.setVerticalGroup(
            popupWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupWindowLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(okPopupWinBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        setMaximumSize(new java.awt.Dimension(111111, 111111));
        setMinimumSize(new java.awt.Dimension(450, 375));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${maximumSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("maximumSize"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${minimumSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), mainPanel, org.jdesktop.beansbinding.BeanProperty.create("preferredSize"));
        bindingGroup.addBinding(binding);

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPane.setBackground(new java.awt.Color(51, 163, 252));
        loginPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginPane.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        loginPane.setMaximumSize(new java.awt.Dimension(111111, 11111));
        loginPane.setMinimumSize(new java.awt.Dimension(450, 375));
        loginPane.setPreferredSize(new java.awt.Dimension(450, 375));
        loginPane.setLayout(new javax.swing.BoxLayout(loginPane, javax.swing.BoxLayout.X_AXIS));

        jPanel11.setBackground(new java.awt.Color(51, 163, 252));
        jPanel11.setPreferredSize(new java.awt.Dimension(125, 404));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        loginPane.add(jPanel11);

        jPanel9.setBackground(new java.awt.Color(51, 163, 252));
        jPanel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel16.setBackground(new java.awt.Color(51, 163, 252));
        jPanel16.setMaximumSize(new java.awt.Dimension(249, 134));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jPanel38.setBackground(new java.awt.Color(51, 163, 252));
        jPanel38.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel38.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel38.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel38.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("passman/Bundle"); // NOI18N
        jLabel16.setText(bundle.getString("PLEASELOGIN")); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setMaximumSize(new java.awt.Dimension(123123, 1123127));
        jLabel16.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel16.setPreferredSize(new java.awt.Dimension(40, 45));
        jPanel38.add(jLabel16, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel38);

        jPanel36.setBackground(new java.awt.Color(51, 163, 252));
        jPanel36.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel36.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel36.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setLabelFor(loginUsername);
        jLabel11.setText(bundle.getString("USERNAME")); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel11.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 40));
        jPanel36.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel36);

        loginUsername.setMinimumSize(new java.awt.Dimension(0, 0));
        loginUsername.setPreferredSize(new java.awt.Dimension(0, 40));
        jPanel16.add(loginUsername);

        jPanel37.setBackground(new java.awt.Color(51, 163, 252));
        jPanel37.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel37.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel37.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel37.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setLabelFor(loginPassword);
        jLabel12.setText(bundle.getString("PASSWORD")); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel12.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel12.setPreferredSize(new java.awt.Dimension(0, 40));
        jPanel37.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel37);

        loginPassword.setMinimumSize(new java.awt.Dimension(0, 0));
        loginPassword.setPreferredSize(new java.awt.Dimension(0, 40));
        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });
        jPanel16.add(loginPassword);

        jPanel21.setBackground(new java.awt.Color(51, 163, 252));
        jPanel21.setLayout(new java.awt.BorderLayout());

        attemptLogin.setBackground(new java.awt.Color(172, 198, 219));
        attemptLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        attemptLogin.setText(bundle.getString("LOGIN")); // NOI18N
        attemptLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        attemptLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attemptLogin.setMaximumSize(new java.awt.Dimension(70, 40));
        attemptLogin.setMinimumSize(new java.awt.Dimension(40, 20));
        attemptLogin.setPreferredSize(new java.awt.Dimension(50, 20));
        attemptLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptLoginActionPerformed(evt);
            }
        });
        jPanel21.add(attemptLogin, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel21);

        jPanel9.add(jPanel16);

        jPanel14.setBackground(new java.awt.Color(51, 163, 252));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(51, 163, 252));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15);

        loginPane.add(jPanel9);

        jPanel13.setBackground(new java.awt.Color(51, 163, 252));
        jPanel13.setPreferredSize(new java.awt.Dimension(125, 404));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        loginPane.add(jPanel13);

        mainPanel.add(loginPane, "LOGIN");

        mainPane.setBackground(new java.awt.Color(51, 163, 252));
        mainPane.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(51, 163, 252));
        jPanel10.setMinimumSize(new java.awt.Dimension(50, 90));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 90));
        jPanel10.setLayout(new java.awt.GridLayout(0, 1));

        addEntryBtn.setBackground(new java.awt.Color(172, 198, 219));
        addEntryBtn.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        addEntryBtn.setText(bundle.getString("ADD")); // NOI18N
        addEntryBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        addEntryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryBtnActionPerformed(evt);
            }
        });
        jPanel10.add(addEntryBtn);

        viewListBtn.setBackground(new java.awt.Color(172, 198, 219));
        viewListBtn.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        viewListBtn.setText(bundle.getString("VIEW")); // NOI18N
        viewListBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        viewListBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListBtnActionPerformed(evt);
            }
        });
        jPanel10.add(viewListBtn);
        jPanel10.add(filler8);

        mainPane.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel12.setBackground(new java.awt.Color(51, 163, 252));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel39.setBackground(new java.awt.Color(51, 163, 252));
        jPanel39.setLayout(new javax.swing.BoxLayout(jPanel39, javax.swing.BoxLayout.Y_AXIS));

        jPanel42.setBackground(new java.awt.Color(51, 163, 252));
        jPanel42.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel42.setPreferredSize(new java.awt.Dimension(439, 40));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel39.add(jPanel42);

        jPanel41.setBackground(new java.awt.Color(51, 163, 252));
        jPanel41.setLayout(new javax.swing.BoxLayout(jPanel41, javax.swing.BoxLayout.Y_AXIS));

        jPanel43.setBackground(new java.awt.Color(51, 163, 252));
        jPanel43.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel43.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel43.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jLabel17.setText(bundle.getString("QUICKSEARCH")); // NOI18N
        jLabel17.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel17.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel43.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel43);

        jPanel44.setBackground(new java.awt.Color(51, 163, 252));
        jPanel44.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel44.setPreferredSize(new java.awt.Dimension(439, 20));
        jPanel44.setLayout(new java.awt.BorderLayout());

        quickSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickSearchFieldActionPerformed(evt);
            }
        });
        jPanel44.add(quickSearchField, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel44);

        jPanel39.add(jPanel41);

        jPanel12.add(jPanel39);

        jPanel40.setBackground(new java.awt.Color(51, 163, 252));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel40);

        mainPane.add(jPanel12, java.awt.BorderLayout.CENTER);

        mainPanel.add(mainPane, "MAIN");

        globalViewPane.setBackground(new java.awt.Color(51, 163, 252));
        globalViewPane.setToolTipText(bundle.getString("SHOW")); // NOI18N
        globalViewPane.setMaximumSize(new java.awt.Dimension(111111, 111111));
        globalViewPane.setMinimumSize(new java.awt.Dimension(450, 375));
        globalViewPane.setPreferredSize(new java.awt.Dimension(500, 425));
        globalViewPane.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 163, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(50, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        jList1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler3, java.awt.BorderLayout.SOUTH);

        globalViewPane.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(51, 163, 252));
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(filler1, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(51, 163, 252));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        removeEntryBtn.setBackground(new java.awt.Color(172, 198, 219));
        removeEntryBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        removeEntryBtn.setText(bundle.getString("REMOVE")); // NOI18N
        removeEntryBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        removeEntryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEntryBtnActionPerformed(evt);
            }
        });
        jPanel3.add(removeEntryBtn);

        toggleShowPassword.setBackground(new java.awt.Color(172, 198, 219));
        toggleShowPassword.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        toggleShowPassword.setText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.setToolTipText(bundle.getString("SHOW")); // NOI18N
        toggleShowPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        toggleShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePassVisibility(evt);
            }
        });
        jPanel3.add(toggleShowPassword);

        addNewEntryBtn.setBackground(new java.awt.Color(172, 198, 219));
        addNewEntryBtn.setText(bundle.getString("ADD")); // NOI18N
        addNewEntryBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        addNewEntryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEntryBtnActionPerformed(evt);
            }
        });
        jPanel3.add(addNewEntryBtn);

        copyToClip.setBackground(new java.awt.Color(172, 198, 219));
        copyToClip.setText(bundle.getString("COPY")); // NOI18N
        copyToClip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        copyToClip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        copyToClip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipActionPerformed(evt);
            }
        });
        jPanel3.add(copyToClip);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(51, 163, 252));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBackground(new java.awt.Color(51, 163, 252));
        jPanel5.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText(bundle.getString("LABEL")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel5.add(jLabel2, java.awt.BorderLayout.WEST);

        labelShow.setEditable(false);
        labelShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelShow.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel5.add(labelShow, java.awt.BorderLayout.CENTER);
        jPanel5.add(filler4, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 163, 252));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setText(bundle.getString("USERNAME")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);

        usernameShow.setEditable(false);
        usernameShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        usernameShow.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel6.add(usernameShow, java.awt.BorderLayout.CENTER);
        jPanel6.add(filler5, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(51, 163, 252));
        jPanel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setText(bundle.getString("PASSWORD")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel7.add(jLabel5, java.awt.BorderLayout.WEST);

        passwordShow.setEditable(false);
        passwordShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        passwordShow.setText("null");
        passwordShow.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        passwordShow.setPreferredSize(new java.awt.Dimension(6, 20));
        jPanel7.add(passwordShow, java.awt.BorderLayout.CENTER);
        jPanel7.add(filler6, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(51, 163, 252));
        jPanel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(bundle.getString("COMMENTS")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel8.add(jLabel3, java.awt.BorderLayout.WEST);

        commentShow.setEditable(false);
        commentShow.setColumns(20);
        commentShow.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        commentShow.setLineWrap(true);
        commentShow.setRows(5);
        commentShow.setWrapStyleWord(true);
        jScrollPane3.setViewportView(commentShow);

        jPanel8.add(jScrollPane3, java.awt.BorderLayout.CENTER);
        jPanel8.add(filler7, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel8);
        jPanel4.add(filler2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        globalViewPane.add(jPanel2, java.awt.BorderLayout.CENTER);

        mainPanel.add(globalViewPane, "GLOBAL");

        addEntryPane.setBackground(new java.awt.Color(51, 163, 252));
        addEntryPane.setMaximumSize(new java.awt.Dimension(450, 300));
        addEntryPane.setMinimumSize(new java.awt.Dimension(450, 300));
        addEntryPane.setPreferredSize(new java.awt.Dimension(450, 300));
        addEntryPane.setLayout(new javax.swing.BoxLayout(addEntryPane, javax.swing.BoxLayout.LINE_AXIS));

        jPanel17.setBackground(new java.awt.Color(51, 163, 252));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 204));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        addEntryPane.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(51, 163, 252));
        jPanel18.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel18.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.X_AXIS));

        jPanel20.setBackground(new java.awt.Color(51, 163, 252));
        jPanel20.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setBackground(new java.awt.Color(51, 163, 252));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setLabelFor(newLabel);
        jLabel9.setText(bundle.getString("LABEL")); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setMaximumSize(new java.awt.Dimension(40, 45));
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 45));
        jPanel25.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel25);

        newLabel.setMinimumSize(new java.awt.Dimension(100, 25));
        newLabel.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel20.add(newLabel);

        jPanel26.setBackground(new java.awt.Color(51, 163, 252));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setLabelFor(newUsername);
        jLabel4.setText(bundle.getString("USERNAME")); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setMaximumSize(new java.awt.Dimension(98746, 89451));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 45));
        jPanel26.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel26);

        newUsername.setMinimumSize(new java.awt.Dimension(100, 25));
        newUsername.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel20.add(newUsername);

        jPanel22.setBackground(new java.awt.Color(51, 163, 252));
        jPanel22.setMaximumSize(new java.awt.Dimension(98816, 40));
        jPanel22.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel22.setPreferredSize(new java.awt.Dimension(0, 20));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.X_AXIS));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setLabelFor(newPassword);
        jLabel7.setText(bundle.getString("PASSWORD")); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setMaximumSize(new java.awt.Dimension(98746, 89451));
        jLabel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 45));
        jPanel22.add(jLabel7);

        generateBtn.setBackground(new java.awt.Color(172, 198, 219));
        generateBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        generateBtn.setText(bundle.getString("GENERATE")); // NOI18N
        generateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        generateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generateBtn.setMaximumSize(new java.awt.Dimension(100, 40));
        generateBtn.setMinimumSize(new java.awt.Dimension(60, 20));
        generateBtn.setPreferredSize(new java.awt.Dimension(70, 20));
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });
        jPanel22.add(generateBtn);

        pGenerationOptionsBtn.setText(bundle.getString("OPTIONS")); // NOI18N
        pGenerationOptionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGenerationOptionsBtnActionPerformed(evt);
            }
        });
        jPanel22.add(pGenerationOptionsBtn);

        jPanel20.add(jPanel22);

        newPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        newPassword.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel20.add(newPassword);

        jPanel27.setBackground(new java.awt.Color(51, 163, 252));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setLabelFor(newComment);
        jLabel10.setText(bundle.getString("COMMENTS")); // NOI18N
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setMaximumSize(new java.awt.Dimension(98746, 89451));
        jLabel10.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 45));
        jPanel27.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel27);

        newComment.setColumns(20);
        newComment.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newComment.setLineWrap(true);
        newComment.setRows(4);
        newComment.setWrapStyleWord(true);
        jScrollPane2.setViewportView(newComment);

        jPanel20.add(jScrollPane2);

        confirmEntryBtn.setBackground(new java.awt.Color(172, 198, 219));
        confirmEntryBtn.setText(bundle.getString("CREATE")); // NOI18N
        confirmEntryBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        confirmEntryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEntryBtnActionPerformed(evt);
            }
        });
        jPanel20.add(confirmEntryBtn);

        jPanel23.setBackground(new java.awt.Color(51, 163, 252));
        jPanel23.setPreferredSize(new java.awt.Dimension(229, 200));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel23);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel20.add(jPanel24);

        jPanel18.add(jPanel20);

        addEntryPane.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(51, 163, 252));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 204));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        addEntryPane.add(jPanel19);

        mainPanel.add(addEntryPane, "ADD");

        languagePane.setBackground(new java.awt.Color(51, 163, 252));
        languagePane.setMaximumSize(new java.awt.Dimension(450, 300));
        languagePane.setMinimumSize(new java.awt.Dimension(450, 300));
        languagePane.setPreferredSize(new java.awt.Dimension(450, 300));

        portuguese.setBackground(new java.awt.Color(51, 163, 252));
        buttonGroup1.add(portuguese);
        portuguese.setText(bundle.getString("PORTUGUESE")); // NOI18N
        portuguese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portugueseActionPerformed(evt);
            }
        });

        english.setBackground(new java.awt.Color(51, 163, 252));
        buttonGroup1.add(english);
        english.setText(bundle.getString("ENGLISH")); // NOI18N
        english.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishActionPerformed(evt);
            }
        });

        jLabel6.setText(bundle.getString("BELOW YOU CAN CHOOSE YOUR PREFERRED LANGUAGE.")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel8.setText(bundle.getString("CHANGES WILL ONLY BE VISIBLE AFTER RESTARTING THE APPLICATION.")); // NOI18N

        homeBtn.setBackground(new java.awt.Color(172, 198, 219));
        homeBtn.setText(bundle.getString("BACK")); // NOI18N
        homeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        languageOK.setBackground(new java.awt.Color(172, 198, 219));
        languageOK.setText(bundle.getString("OK")); // NOI18N
        languageOK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        languageOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        languageOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languagePaneLayout = new javax.swing.GroupLayout(languagePane);
        languagePane.setLayout(languagePaneLayout);
        languagePaneLayout.setHorizontalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languagePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(languageOK)
                    .addComponent(jLabel8)
                    .addComponent(english)
                    .addComponent(portuguese)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        languagePaneLayout.setVerticalGroup(
            languagePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languagePaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(portuguese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(english)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languageOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(homeBtn)
                .addContainerGap())
        );

        mainPanel.add(languagePane, "LANGUAGE");

        createUserPane.setBackground(new java.awt.Color(51, 163, 252));
        createUserPane.setLayout(new javax.swing.BoxLayout(createUserPane, javax.swing.BoxLayout.X_AXIS));

        jPanel28.setBackground(new java.awt.Color(51, 163, 252));
        jPanel28.setPreferredSize(new java.awt.Dimension(125, 404));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        createUserPane.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(51, 163, 252));
        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.Y_AXIS));

        jPanel33.setBackground(new java.awt.Color(51, 163, 252));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(bundle.getString("USERNAME")); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel33.add(jLabel13, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel33);

        newUserField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserField.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanel29.add(newUserField);

        jPanel32.setBackground(new java.awt.Color(51, 163, 252));
        jPanel32.setPreferredSize(new java.awt.Dimension(0, 20));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText(bundle.getString("PASSWORD")); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setMaximumSize(new java.awt.Dimension(61, 40));
        jLabel14.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel14.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel32.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel32);

        newUserPasswordField.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanel29.add(newUserPasswordField);

        jPanel35.setBackground(new java.awt.Color(51, 163, 252));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText(bundle.getString("REPEATPASS")); // NOI18N
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel35.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel35);

        newUserPasswordField2.setMinimumSize(new java.awt.Dimension(110, 20));
        newUserPasswordField2.setPreferredSize(new java.awt.Dimension(110, 20));
        jPanel29.add(newUserPasswordField2);

        jPanel31.setBackground(new java.awt.Color(51, 163, 252));
        jPanel31.setLayout(new java.awt.BorderLayout());

        createUserBtn.setBackground(new java.awt.Color(172, 198, 219));
        createUserBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        createUserBtn.setText(bundle.getString("CONFIRMACC")); // NOI18N
        createUserBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        createUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });
        jPanel31.add(createUserBtn, java.awt.BorderLayout.CENTER);

        cancelCreateAcc.setBackground(new java.awt.Color(172, 198, 219));
        cancelCreateAcc.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        cancelCreateAcc.setText(bundle.getString("CANCEL")); // NOI18N
        cancelCreateAcc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        cancelCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelCreateAcc.setMargin(new java.awt.Insets(2, 2, 2, 2));
        cancelCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCreateAccActionPerformed(evt);
            }
        });
        jPanel31.add(cancelCreateAcc, java.awt.BorderLayout.EAST);

        jPanel29.add(jPanel31);

        jPanel34.setBackground(new java.awt.Color(51, 163, 252));
        jPanel34.setPreferredSize(new java.awt.Dimension(0, 200));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel34);

        createUserPane.add(jPanel29);

        jPanel30.setBackground(new java.awt.Color(51, 163, 252));
        jPanel30.setPreferredSize(new java.awt.Dimension(125, 404));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        createUserPane.add(jPanel30);

        mainPanel.add(createUserPane, "CREATEUSER");

        accountOptionsPane.setBackground(new java.awt.Color(51, 163, 252));
        accountOptionsPane.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        accountOptionsPane.setMinimumSize(new java.awt.Dimension(450, 375));
        accountOptionsPane.setPreferredSize(new java.awt.Dimension(450, 375));
        accountOptionsPane.setLayout(new java.awt.BorderLayout());

        jPanel45.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel45.setPreferredSize(new java.awt.Dimension(150, 0));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel47.setLayout(new java.awt.GridLayout(0, 1));

        changeUsernameButton.setBackground(new java.awt.Color(172, 198, 219));
        changeUsernameButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        changeUsernameButton.setText(bundle.getString("CHANGEUSER")); // NOI18N
        changeUsernameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        changeUsernameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeUsernameButton.setMaximumSize(new java.awt.Dimension(37000, 37000));
        changeUsernameButton.setMinimumSize(new java.awt.Dimension(50, 40));
        changeUsernameButton.setPreferredSize(new java.awt.Dimension(100, 50));
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });
        jPanel47.add(changeUsernameButton);

        changePasswordButton.setBackground(new java.awt.Color(172, 198, 219));
        changePasswordButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        changePasswordButton.setText(bundle.getString("CHANGEPASS")); // NOI18N
        changePasswordButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        changePasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordButton.setMaximumSize(new java.awt.Dimension(37000, 37000));
        changePasswordButton.setMinimumSize(new java.awt.Dimension(50, 40));
        changePasswordButton.setPreferredSize(new java.awt.Dimension(100, 50));
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });
        jPanel47.add(changePasswordButton);

        deleteAccBtn.setBackground(new java.awt.Color(172, 198, 219));
        deleteAccBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        deleteAccBtn.setText(bundle.getString("DELETEACC")); // NOI18N
        deleteAccBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        deleteAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteAccBtn.setMaximumSize(new java.awt.Dimension(37000, 37000));
        deleteAccBtn.setMinimumSize(new java.awt.Dimension(50, 40));
        deleteAccBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        deleteAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccBtnActionPerformed(evt);
            }
        });
        jPanel47.add(deleteAccBtn);

        backFromAccOptsBtn.setBackground(new java.awt.Color(172, 198, 219));
        backFromAccOptsBtn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        backFromAccOptsBtn.setText(bundle.getString("BACK")); // NOI18N
        backFromAccOptsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 89, 89), 2));
        backFromAccOptsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backFromAccOptsBtn.setMaximumSize(new java.awt.Dimension(37000, 37000));
        backFromAccOptsBtn.setMinimumSize(new java.awt.Dimension(50, 40));
        backFromAccOptsBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        backFromAccOptsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFromAccOptsBtnActionPerformed(evt);
            }
        });
        jPanel47.add(backFromAccOptsBtn);

        jPanel45.add(jPanel47, java.awt.BorderLayout.NORTH);

        jPanel48.setBackground(new java.awt.Color(51, 163, 252));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        jPanel45.add(jPanel48, java.awt.BorderLayout.CENTER);

        accountOptionsPane.add(jPanel45, java.awt.BorderLayout.WEST);

        jPanel46.setBackground(new java.awt.Color(51, 163, 252));
        jPanel46.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        accountOptionsPane.add(jPanel46, java.awt.BorderLayout.CENTER);

        mainPanel.add(accountOptionsPane, "ACCOPTIONS");

        jMenu1.setText(bundle.getString("FILE")); // NOI18N
        jMenu1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        createAccMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        createAccMenuItem.setText(bundle.getString("CREATEACC")); // NOI18N
        createAccMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(createAccMenuItem);

        addEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        addEntry.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addEntry.setText(bundle.getString("ADD")); // NOI18N
        addEntry.setEnabled(false);
        addEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryActionPerformed(evt);
            }
        });
        jMenu1.add(addEntry);

        viewList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        viewList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewList.setText(bundle.getString("VIEW")); // NOI18N
        viewList.setEnabled(false);
        viewList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListActionPerformed(evt);
            }
        });
        jMenu1.add(viewList);

        logoutMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logoutMenuItem.setText(bundle.getString("LOGOUT")); // NOI18N
        logoutMenuItem.setEnabled(false);
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("OPTIONS")); // NOI18N
        jMenu2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        languageMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        languageMenu.setText(bundle.getString("LANGUAGE")); // NOI18N
        languageMenu.setName("languageMenuItem"); // NOI18N
        languageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageMenuActionPerformed(evt);
            }
        });
        jMenu2.add(languageMenu);

        accountMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        accountMenu.setText(bundle.getString("ACCOUNT")); // NOI18N
        accountMenu.setEnabled(false);
        accountMenu.setName(""); // NOI18N
        accountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountMenuActionPerformed(evt);
            }
        });
        jMenu2.add(accountMenu);

        pGenerationMenuItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pGenerationMenuItem.setText(bundle.getString("PGENERATION")); // NOI18N
        pGenerationMenuItem.setEnabled(false);
        pGenerationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGenerationMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(pGenerationMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is triggered when the user clicks the "Add" button.
     * @param evt 
     */
    private void addEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addEntryActionPerformed

    /**
     * This is triggered when the user clicks the "Create" button.
     * @param evt 
     */
    private void confirmEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEntryBtnActionPerformed
        // Calls method that encrypts the password using the current user values and saves entry to DB
        if(Utils.addToDBFromUI(newLabel.getText(), newUsername.getText(), newPassword.getText(), newComment.getText())){        
            // Clears fields
            Utils.clearTextFields(new Component[]{newLabel, newUsername, newPassword, newComment});

            // moves to main screen
            Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
        }
    }//GEN-LAST:event_confirmEntryBtnActionPerformed

    /**
     * This is triggered when the user changes his list selection
     * @param evt 
     */
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        Utils.presentSelectedEntry(jList1, labelShow, usernameShow, passwordShow, commentShow, toggleShowPassword, removeEntryBtn, copyToClip);
    }//GEN-LAST:event_jList1ValueChanged

    private void viewListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListBtnActionPerformed
        
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
        
        // Disables buttons
        Utils.toggleEnabledButtons(false, new Component[]{removeEntryBtn, toggleShowPassword, copyToClip});
        //removeEntryBtn.setEnabled(false);
        //toggleShowPassword.setEnabled(false);
        //copyToClip.setEnabled(false);
        
    }//GEN-LAST:event_viewListBtnActionPerformed

    private void addEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryBtnActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addEntryBtnActionPerformed

    private void viewListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListActionPerformed
        utils.refreshView(jList1, mainPanel);
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
    }//GEN-LAST:event_viewListActionPerformed

    private void languageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageMenuActionPerformed
        if(Utils.loadParams().get(1).equals("pt")){ //NOI18N
            portuguese.setSelected(true);
        }
        else {
            english.setSelected(true);
        }
        Utils.goToScreen(mainPanel, "LANGUAGE"); //NOI18N
    }//GEN-LAST:event_languageMenuActionPerformed

    private void portugueseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portugueseActionPerformed
        utils.saveParamChanges("pt", "PT"); //NOI18N
    }//GEN-LAST:event_portugueseActionPerformed

    private void englishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishActionPerformed
        utils.saveParamChanges("en", "UK"); //NOI18N
    }//GEN-LAST:event_englishActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_homeBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        newPassword.setText(Utils.generateNewRandomPassword());
    }//GEN-LAST:event_generateBtnActionPerformed

    private void okPopupWinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPopupWinBtnActionPerformed
        // disposes popup window
        popupWindow.dispose();
    }//GEN-LAST:event_okPopupWinBtnActionPerformed

    /**
     * This is triggered when the user toggles the password visibility
     * @param evt 
     */
    private void togglePassVisibility(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePassVisibility
        if(toggleShowPassword.isSelected()){
            Model thisModel = (Model)jList1.getSelectedValue();
            String plainTextPassword = Utils.getFromDBToUI(thisModel.getPassword(),thisModel.getSalt());

            passwordShow.setText(plainTextPassword);
        } else{
            passwordShow.setText("*********"); //NOI18N
        }
    }//GEN-LAST:event_togglePassVisibility

    /**
     * This is triggered when the user confirms the creation of an account
     * @param evt 
     */
    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // make sure both passwords are the same
        if(Arrays.equals(newUserPasswordField.getPassword(),newUserPasswordField2.getPassword())){
            // Make sure new username is not an empty string
            if(!newUserField.getText().isEmpty()){
                if(Utils.createNewUser(newUserField.getText(), new String(newUserPasswordField.getPassword())) == 0){
                    // Log action
                    Logger.getLogger("").log(Level.INFO, "User {0} added to database.", newUserField.getText());
                    // Clears fields
                    Utils.clearTextFields(new Component[]{newUserField, newUserPasswordField, newUserPasswordField2});
                    // Goes to login screen
                    Utils.goToScreen(mainPanel, "LOGIN"); //NOI18N
                } else{
                    ErrorDialog errDlg = new ErrorDialog(new JFrame(), java.util.ResourceBundle.getBundle("passman/Bundle").getString("INVALIDUSERNAME"), java.util.ResourceBundle.getBundle("passman/Bundle").getString("USERNAMEEXISTS"));
                }
            } else{ // Username is empty
                ErrorDialog errDlg = new ErrorDialog(new JFrame(), java.util.ResourceBundle.getBundle("passman/Bundle").getString("INVALIDUSERNAME"), java.util.ResourceBundle.getBundle("passman/Bundle").getString("USERNAMEEMPTY"));
            }
        } else{ // Passwords are not the same
            ErrorDialog errDlg = new ErrorDialog(new JFrame(), java.util.ResourceBundle.getBundle("passman/Bundle").getString("PASSWORDSDIFFER"), java.util.ResourceBundle.getBundle("passman/Bundle").getString("PASSWORDSDIFFERMSG"));
        }
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void createAccMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccMenuItemActionPerformed
        Utils.goToScreen(mainPanel, "CREATEUSER"); //NOI18N
    }//GEN-LAST:event_createAccMenuItemActionPerformed

    /**
     * This is triggered when the user wants to login
     * @param evt 
     */
    private void attemptLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptLoginActionPerformed
        if(Utils.tryLogin(loginUsername.getText(), new String(loginPassword.getPassword()))){
            // Goes to main screen
            Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
            
            // Clears fields
            Utils.clearTextFields(new Component[]{loginUsername, loginPassword});
            
            Utils.toggleMenus(jMenu1, true);
            Utils.toggleMenus(jMenu2, true);
        } else{ // Login failed
            ErrorDialog errDlg = new ErrorDialog(new JFrame(), java.util.ResourceBundle.getBundle("passman/Bundle").getString("LOGINFAILED"), java.util.ResourceBundle.getBundle("passman/Bundle").getString("LOGINFAILEDMSG"));
        }
    }//GEN-LAST:event_attemptLoginActionPerformed

    private void removeEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEntryBtnActionPerformed
        Model model = (Model)jList1.getSelectedValue();

        SQLiteJDBC sqlite = new SQLiteJDBC();
        sqlite.removeItem2(model);
        // Log action
        Logger.getLogger("").log(Level.INFO, "Entry with label {0} removed from database.", model.getLabel());

        utils.refreshView(jList1, mainPanel);

        // Clears fields
        Utils.clearTextFields(new Component[]{labelShow, usernameShow, passwordShow, commentShow});

        // Deselects items in list
        jList1.setSelectedIndex(-1);
    }//GEN-LAST:event_removeEntryBtnActionPerformed

    private void addNewEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEntryBtnActionPerformed
        Utils.goToScreen(mainPanel, "ADD"); //NOI18N
    }//GEN-LAST:event_addNewEntryBtnActionPerformed

    private void copyToClipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipActionPerformed
        Model thisModel = (Model)jList1.getSelectedValue();
        String str = Utils.getFromDBToUI(thisModel.getPassword(),thisModel.getSalt());
        StringSelection stringSelection = new StringSelection (str);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_copyToClipActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        
        // Log action
        Logger.getLogger("").log(Level.INFO, "User {0} logged out.",Utils.getCurrentUser()); //NOI18N
        
        Utils.logout(jList1, mainPanel);
        Utils.toggleMenus(jMenu1, false);
        Utils.toggleMenus(jMenu2, false);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void cancelCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCreateAccActionPerformed
        // Clears fields
        Utils.clearTextFields(new Component[]{newUserField, newUserPasswordField, newUserPasswordField2});
        
        Utils.goToScreen(mainPanel, "LOGIN"); //NOI18N
    }//GEN-LAST:event_cancelCreateAccActionPerformed

    private void languageOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageOKActionPerformed
        if("".equals(Utils.getCurrentUser()) || Utils.getCurrentUser()==null){ //NOI18N
            Utils.goToScreen(mainPanel, "LOGIN"); //NOI18N
        } else{
            utils.refreshView(jList1, mainPanel);
            Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
        }        
    }//GEN-LAST:event_languageOKActionPerformed

    private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
        if(Utils.tryLogin(loginUsername.getText(), new String(loginPassword.getPassword()))){
            // Goes to main screen
            Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
            // Clears fields
            Utils.clearTextFields(new Component[]{loginUsername, loginPassword});
            
            Utils.toggleMenus(jMenu1, true);
            Utils.toggleMenus(jMenu2, true);
        } else{ // Login failed
            ErrorDialog errDlg = new ErrorDialog(new JFrame(), java.util.ResourceBundle.getBundle("passman/Bundle").getString("LOGINFAILED"), java.util.ResourceBundle.getBundle("passman/Bundle").getString("LOGINFAILEDMSG"));
        }
    }//GEN-LAST:event_loginPasswordActionPerformed

    private void quickSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickSearchFieldActionPerformed
        SQLiteJDBC sqlite = new SQLiteJDBC();
        List<Model> list = new ArrayList<>(sqlite.getItems2());
        
        Collections.sort(list, (Model m1, Model m2) -> {
            return(m1.getLabel().compareToIgnoreCase(m2.getLabel()));
        });        
        utils.refreshView(jList1, mainPanel, list);
        
        String searchStr = quickSearchField.getText();
        
        Pattern pat = Pattern.compile("^"+searchStr); //NOI18N
        Matcher matcher;
        
        int i,c;
        ListModel<Model> dm = jList1.getModel();
        c=dm.getSize();
        for(i=0;i<c;i++){
            matcher = pat.matcher(dm.getElementAt(i).toString());
            if(matcher.find()){
                jList1.setSelectedIndex(i);
                jList1.ensureIndexIsVisible(i);
                jList1.repaint();
                break;
            }
        }
        
        Utils.goToScreen(mainPanel, "GLOBAL"); //NOI18N
    }//GEN-LAST:event_quickSearchFieldActionPerformed

    private void accountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountMenuActionPerformed
        Utils.goToScreen(mainPanel, "ACCOPTIONS"); //NOI18N
    }//GEN-LAST:event_accountMenuActionPerformed

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        ChangeUsernameDialog changeUsernameDialog = new ChangeUsernameDialog(this, true);
        int result = changeUsernameDialog.showDialog();
        
        // If name changing was successful logs out to allow user to relog
        if(result==0){
            Utils.logout(jList1, mainPanel);
            Utils.toggleMenus(jMenu1, false);
            Utils.toggleMenus(jMenu2, false);
        } else{
            // Action canceled
        }
    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        ChangePasswordDialog changePasswordDialog = new ChangePasswordDialog(this, true);
        int result = changePasswordDialog.showDialog();
        
        if(result==0){
            Utils.logout(jList1, mainPanel);
            Utils.toggleMenus(jMenu1, false);
            Utils.toggleMenus(jMenu2, false);
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void backFromAccOptsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFromAccOptsBtnActionPerformed
        Utils.goToScreen(mainPanel, "MAIN"); //NOI18N
    }//GEN-LAST:event_backFromAccOptsBtnActionPerformed

    private void pGenerationOptionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGenerationOptionsBtnActionPerformed
        PasswordOptionsDialog passOptDialog = new PasswordOptionsDialog(this, true);
        PasswordOptions pOpts = Utils.loadPasswordOptions();
        pOpts = passOptDialog.showDialog(pOpts);
        if(pOpts != null){
           Utils.savePasswordOptions(pOpts);
            // Log action
            Logger.getLogger("").log(Level.INFO, "Password properties saved."); //NOI18N
        }
    }//GEN-LAST:event_pGenerationOptionsBtnActionPerformed

    private void pGenerationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGenerationMenuItemActionPerformed
        PasswordOptionsDialog passOptDialog = new PasswordOptionsDialog(this, true);
        PasswordOptions pOpts = Utils.loadPasswordOptions();
        pOpts = passOptDialog.showDialog(pOpts);
        if(pOpts != null){
           Utils.savePasswordOptions(pOpts);
            // Log action
            Logger.getLogger("").log(Level.INFO, "Password properties saved."); //NOI18N
        }
    }//GEN-LAST:event_pGenerationMenuItemActionPerformed

    private void deleteAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccBtnActionPerformed
        DeleteAccountDialog delAccDialog = new DeleteAccountDialog(this, true);
        int result = delAccDialog.showDialog();
        
        if(result==0){
            Utils.logout(jList1, mainPanel);
            Utils.toggleMenus(jMenu1, false);
            Utils.toggleMenus(jMenu2, false);
        }
    }//GEN-LAST:event_deleteAccBtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("passman/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassManUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Logger config
        try{
            SimpleDateFormat format = new SimpleDateFormat("MM-dd"); //NOI18N
            String logName = "PassManJ_logger%u_"+format.format(new Date())+".log"; //NOI18N
            Handler handler = new FileHandler(logName, 10000, 1, true);
            handler.setFormatter(new SimpleFormatter());
            Logger.getLogger("").addHandler(handler); //NOI18N
        } catch(IOException | SecurityException e){            
            ErrorDialog errDlg = new ErrorDialog(new JFrame(), e.getClass().getName(), e.getMessage());
            System.exit(0);
        }
        // Set location (language) according to user preferences
        List<String> list = Utils.loadParams();
        Locale.setDefault(new Locale(list.get(1),list.get(0)));

        // Creates DB if it doesn't exist
        Utils.verifyDB();
                
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PassManUI myFrame = new PassManUI();
                myFrame.setTitle(Utils.getTitleFromProps());
                myFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accountMenu;
    private javax.swing.JPanel accountOptionsPane;
    private javax.swing.JMenuItem addEntry;
    private javax.swing.JButton addEntryBtn;
    private javax.swing.JPanel addEntryPane;
    private javax.swing.JButton addNewEntryBtn;
    private javax.swing.JButton attemptLogin;
    private javax.swing.JButton backFromAccOptsBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelCreateAcc;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton changeUsernameButton;
    private javax.swing.JTextArea commentShow;
    private javax.swing.JButton confirmEntryBtn;
    private javax.swing.JButton copyToClip;
    private javax.swing.JMenuItem createAccMenuItem;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JPanel createUserPane;
    private javax.swing.JButton deleteAccBtn;
    private javax.swing.JRadioButton english;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton generateBtn;
    private javax.swing.JPanel globalViewPane;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField labelShow;
    private javax.swing.JMenuItem languageMenu;
    private javax.swing.JButton languageOK;
    private javax.swing.JPanel languagePane;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel message;
    private javax.swing.JTextArea newComment;
    private javax.swing.JTextField newLabel;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField newUserField;
    private javax.swing.JPasswordField newUserPasswordField;
    private javax.swing.JPasswordField newUserPasswordField2;
    private javax.swing.JTextField newUsername;
    private javax.swing.JButton okPopupWinBtn;
    private javax.swing.JMenuItem pGenerationMenuItem;
    private javax.swing.JButton pGenerationOptionsBtn;
    private javax.swing.JTextField passwordShow;
    private javax.swing.JDialog popupWindow;
    private javax.swing.JRadioButton portuguese;
    private javax.swing.JTextField quickSearchField;
    private javax.swing.JButton removeEntryBtn;
    private javax.swing.JToggleButton toggleShowPassword;
    private javax.swing.JTextField usernameShow;
    private javax.swing.JMenuItem viewList;
    private javax.swing.JButton viewListBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
