/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passman.model;

/**
 *
 * @author P057736
 */
public class PasswordOptionsDialog extends javax.swing.JDialog {

    /**
     * Creates new form PasswordOptionsDialog
     */
    public PasswordOptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pLengthSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        symbolsCheckBx = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        safeSymbolsCheckBx = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        digitsCheckBx = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        upCaseCheckBx = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cancelPassOptions = new javax.swing.JButton();
        confirmPassOptions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("passman/Bundle"); // NOI18N
        setTitle(bundle.getString("PGENERATION")); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(0, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText(bundle.getString("PLENGTH")); // NOI18N
        jPanel4.add(jLabel1);

        pLengthSpinner.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        pLengthSpinner.setModel(new javax.swing.SpinnerNumberModel(12, 9, 24, 1));
        jPanel4.add(pLengthSpinner);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText(bundle.getString("SYMBOLS")); // NOI18N
        jPanel4.add(jLabel2);

        symbolsCheckBx.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        symbolsCheckBx.setSelected(true);
        jPanel4.add(symbolsCheckBx);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText(bundle.getString("SYMBOLSSAFE")); // NOI18N
        jPanel4.add(jLabel3);

        safeSymbolsCheckBx.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        safeSymbolsCheckBx.setSelected(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, symbolsCheckBx, org.jdesktop.beansbinding.ELProperty.create("${selected}"), safeSymbolsCheckBx, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jPanel4.add(safeSymbolsCheckBx);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText(bundle.getString("DIGITS")); // NOI18N
        jPanel4.add(jLabel4);

        digitsCheckBx.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        digitsCheckBx.setSelected(true);
        jPanel4.add(digitsCheckBx);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText(bundle.getString("UPPERCASE")); // NOI18N
        jPanel4.add(jLabel5);

        upCaseCheckBx.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        upCaseCheckBx.setSelected(true);
        jPanel4.add(upCaseCheckBx);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel6.setLayout(new java.awt.GridLayout());

        cancelPassOptions.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cancelPassOptions.setText(bundle.getString("CANCEL")); // NOI18N
        cancelPassOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPassOptionsActionPerformed(evt);
            }
        });
        jPanel6.add(cancelPassOptions);

        confirmPassOptions.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        confirmPassOptions.setText(bundle.getString("CONFIRMACC")); // NOI18N
        confirmPassOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassOptionsActionPerformed(evt);
            }
        });
        jPanel6.add(confirmPassOptions);

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPassOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassOptionsActionPerformed
        PasswordOptions pOpts = new PasswordOptions((int)pLengthSpinner.getValue(),
                symbolsCheckBx.isSelected(),safeSymbolsCheckBx.isSelected(),
                digitsCheckBx.isSelected(),upCaseCheckBx.isSelected());
        
        result = pOpts;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_confirmPassOptionsActionPerformed

    private void cancelPassOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPassOptionsActionPerformed
        result = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelPassOptionsActionPerformed

    private PasswordOptions result = null;
    
    public PasswordOptions showDialog(PasswordOptions pOpts){
        pLengthSpinner.setValue(pOpts.getpLength());
        symbolsCheckBx.setSelected(pOpts.isSymbols());
        safeSymbolsCheckBx.setSelected(pOpts.isSymbolsSafe());
        digitsCheckBx.setSelected(pOpts.isDigits());
        upCaseCheckBx.setSelected(pOpts.isUpperCase());
        setVisible(true);
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordOptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordOptionsDialog dialog = new PasswordOptionsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPassOptions;
    private javax.swing.JButton confirmPassOptions;
    private javax.swing.JCheckBox digitsCheckBx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner pLengthSpinner;
    private javax.swing.JCheckBox safeSymbolsCheckBx;
    private javax.swing.JCheckBox symbolsCheckBx;
    private javax.swing.JCheckBox upCaseCheckBx;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
